import TopMsg from "@/components/header/TopMsg";
import "./globals.css";
import Nav from "@/components/header/Nav/Nav";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Glasses Ecommerce Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full min-h-full">
        <header className="flex flex-col h-auto">
          <TopMsg />
          <Nav />
        </header>

        <main>{children}</main>
        
        <Footer />
      </body>
    </html>
  );
}
