import TopMsg from "@/components/header/TopMsg";
import "./globals.css";
import NavMenu from "@/components/header/NavMenu";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Glasses Ecommerce Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full min-h-full">
        <header>
          <TopMsg />
          <NavMenu />
        </header>

        <main>{children}</main>
        
        <Footer />
      </body>
    </html>
  );
}
